### ISSUE TITLE
Implement missing CLI commands

### ISSUE THREAD

**Issue by fussel178** [TelestionTeam/telestion-client#263]
Implement the missing commands for the command line interface:

- [x] init
- [x] start
- [ ] build
- [x] generate
- [x] docs
- [x] stats

**Comment by pklaschka** [comment]
`generate` is in the works 😉

**Comment by pklaschka** [comment]
![image](https://user-images.githubusercontent.com/25147704/106988017-f6d2b680-676e-11eb-9035-3bd7fb97fc95.png)
Extensibility concept for the Electron Main process
