### ISSUE TITLE
Update `README.md`

### ISSUE THREAD

**Issue by pklaschka** [TelestionTeam/telestion-client#300]
Some aspects of the repo's `README.md` have become outdated.

We should probably fix wrong and improve missing information (such as missing packages in the _Project Structure_ documentation.

**Comment by fussel178** [comment]
Uii, uii!
Let's add some badges, too!

![CI](https://github.com/TelestionTeam/telestion-client/workflows/CI/badge.svg)
[![lerna](https://img.shields.io/badge/maintained%20with-lerna-cc00ff.svg)](https://lerna.js.org/)
